=== PlentyAg/airbyte-plenty/airbyte-integrations/connectors/source-compusense/source_compusense/schemas/survey_metadata.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1659735821.json",
  "title": "Root",
  "type": "array",
  "default": [],
  "items": {
    "$id": "#root/items",
    "title": "Items",
    "type": "object",
    "required": [
      "testID",
      "testName",
      "testType",
      "day",
      "month",
      "year",
      "location",
      "folderPath",
      "customTestProperties",
      "tags",
      "sections"
    ],
    "properties": {
      "testID": {
        "$id": "#root/items/testID",
        "title": "Testid",
        "type": "integer",
        "default": 0
      },
      "testName": {
        "$id": "#root/items/testName",
        "title": "Testname",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "testType": {
        "$id": "#root/items/testType",
        "title": "Testtype",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "day": {
        "$id": "#root/items/day",
        "title": "Day",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "month": {
        "$id": "#root/items/month",
        "title": "Month",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "year": {
        "$id": "#root/items/year",
        "title": "Year",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "location": {
        "$id": "#root/items/location",
        "title": "Location",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "folderPath": {
        "$id": "#root/items/folderPath",
        "title": "Folderpath",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      },
      "customTestProperties": {
        "$id": "#root/items/customTestProperties",
        "title": "Customtestproperties",
        "type": "array",
        "default": []
      },
      "tags": {
        "$id": "#root/items/tags",
        "title": "Tags",
        "type": "array",
        "default": []
      },
      "sections": {
        "$id": "#root/items/sections",
        "title": "Sections",
        "type": "array",
        "default": [],
        "items": {
          "$id": "#root/items/sections/items",
          "title": "Items",
          "type": "object",
          "required": [
            "sectionNum",
            "sectionName",
            "testType",
            "design",
            "designName",
            "smps",
            "questions"
          ],
          "properties": {
            "sectionNum": {
              "$id": "#root/items/sections/items/sectionNum",
              "title": "Sectionnum",
              "type": "integer",
              "default": 0
            },
            "sectionName": {
              "$id": "#root/items/sections/items/sectionName",
              "title": "Sectionname",
              "type": "string",
              "default": "",
              "pattern": "^.*$"
            },
            "testType": {
              "$id": "#root/items/sections/items/testType",
              "title": "Testtype",
              "type": "string",
              "default": "",
              "pattern": "^.*$"
            },
            "design": {
              "$id": "#root/items/sections/items/design",
              "title": "Design",
              "type": "string",
              "default": "",
              "pattern": "^.*$"
            },
            "designName": {
              "$id": "#root/items/sections/items/designName",
              "title": "Designname",
              "type": "string",
              "default": "",
              "pattern": "^.*$"
            },
            "smps": {
              "$id": "#root/items/sections/items/smps",
              "title": "Smps",
              "type": "array",
              "default": [],
              "items": {
                "$id": "#root/items/sections/items/smps/items",
                "title": "Items",
                "type": "object",
                "required": ["smpNum", "smpName", "smpType", "smpData"],
                "properties": {
                  "smpNum": {
                    "$id": "#root/items/sections/items/smps/items/smpNum",
                    "title": "Smpnum",
                    "type": "integer",
                    "default": 0
                  },
                  "smpName": {
                    "$id": "#root/items/sections/items/smps/items/smpName",
                    "title": "Smpname",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "smpType": {
                    "$id": "#root/items/sections/items/smps/items/smpType",
                    "title": "Smptype",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "smpData": {
                    "$id": "#root/items/sections/items/smps/items/smpData",
                    "title": "Smpdata",
                    "type": "array",
                    "default": []
                  }
                }
              }
            },
            "questions": {
              "$id": "#root/items/sections/items/questions",
              "title": "Questions",
              "type": "array",
              "default": [],
              "items": {
                "$id": "#root/items/sections/items/questions/items",
                "title": "Items",
                "type": "object",
                "required": [
                  "qNum",
                  "aNum",
                  "qName",
                  "qDisplay",
                  "required",
                  "branch",
                  "eCriteria",
                  "qType",
                  "descriptors"
                ],
                "properties": {
                  "qNum": {
                    "$id": "#root/items/sections/items/questions/items/qNum",
                    "title": "Qnum",
                    "type": "integer",
                    "default": 0
                  },
                  "aNum": {
                    "$id": "#root/items/sections/items/questions/items/aNum",
                    "title": "Anum",
                    "type": "integer",
                    "default": 0
                  },
                  "qName": {
                    "$id": "#root/items/sections/items/questions/items/qName",
                    "title": "Qname",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "qDisplay": {
                    "$id": "#root/items/sections/items/questions/items/qDisplay",
                    "title": "Qdisplay",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "required": {
                    "$id": "#root/items/sections/items/questions/items/required",
                    "title": "Required",
                    "type": "boolean",
                    "default": true
                  },
                  "branch": {
                    "$id": "#root/items/sections/items/questions/items/branch",
                    "title": "Branch",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "eCriteria": {
                    "$id": "#root/items/sections/items/questions/items/eCriteria",
                    "title": "Ecriteria",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "qType": {
                    "$id": "#root/items/sections/items/questions/items/qType",
                    "title": "Qtype",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  },
                  "descriptors": {
                    "$id": "#root/items/sections/items/questions/items/descriptors",
                    "title": "Descriptors",
                    "type": "array",
                    "default": []
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== PlentyAg/airbyte-plenty/airbyte-integrations/connectors/source-compusense/source_compusense/sample_files/example-data.json
[
  {
    "testID": 40,
    "testName": "Laramie Happy Hour - Triangle test",
    "testType": "Triangle",
    "day": "31",
    "month": "5",
    "year": "2022",
    "location": "Evaluation Tests",
    "folderPath": "Plenty\\All tests\\Evaluation Tests",
    "customTestProperties": [],
    "tags": [],
    "sections": [
      {
        "sectionNum": 1,
        "sectionName": "First Section",
        "testType": "Triangle",
        "design": "D-40",
        "designName": "1 Triangle Test",
        "smps": [
          { "smpNum": 1, "smpName": "A", "smpType": "Sample", "smpData": [] },
          { "smpNum": 2, "smpName": "B", "smpType": "Sample", "smpData": [] }
        ],
        "questions": [
          {
            "qNum": 1,
            "aNum": 1,
            "qName": "Triangle",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "triangle",
            "descriptors": []
          },
          {
            "qNum": 2,
            "aNum": 1,
            "qName": "Comment",
            "qDisplay": "Triangle response related",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "comment",
            "descriptors": []
          }
        ]
      }
    ]
  },
  {
    "testID": 41,
    "testName": "Laramie Happy Hour - Ranking",
    "testType": "Standard",
    "day": "31",
    "month": "5",
    "year": "2022",
    "location": "Evaluation Tests",
    "folderPath": "Plenty\\All tests\\Evaluation Tests",
    "customTestProperties": [],
    "tags": [],
    "sections": [
      {
        "sectionNum": 1,
        "sectionName": "First Section",
        "testType": "Standard",
        "design": "D-41",
        "designName": "Williams Design (1 Latin Square)",
        "smps": [
          {
            "smpNum": 1,
            "smpName": "Maple Bar",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 2,
            "smpName": "Chocolate Bar",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 3,
            "smpName": "Powdered Donut",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 4,
            "smpName": "Cinnamon Donut",
            "smpType": "Sample",
            "smpData": []
          }
        ],
        "questions": [
          {
            "qNum": 1,
            "aNum": 1,
            "qName": "Sorting",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "binsamples",
            "descriptors": []
          },
          {
            "qNum": 2,
            "aNum": 1,
            "qName": "Ranking",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "ranksamples",
            "descriptors": []
          },
          {
            "qNum": 3,
            "aNum": 1,
            "qName": "Labeled Magnitude Scale - Place a mark on the line to indicate how you feel about your favorite sample as compared to all the other desserts you've eaten before.",
            "qDisplay": "Once (not sample related)",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "linescale",
            "descriptors": [
              { "value": 0.0, "text": "min" },
              { "value": 1.98, "text": "max" }
            ]
          }
        ]
      }
    ]
  },
  {
    "testID": 43,
    "testName": "Tomato test",
    "testType": "Standard",
    "day": "31",
    "month": "5",
    "year": "2022",
    "location": "Evaluation Tests",
    "folderPath": "Plenty\\All tests\\Evaluation Tests",
    "customTestProperties": [],
    "tags": [],
    "sections": [
      {
        "sectionNum": 1,
        "sectionName": "First Section",
        "testType": "Standard",
        "design": "D-43",
        "designName": "Fixed Order",
        "smps": [
          {
            "smpNum": 1,
            "smpName": "8033 Treatment 3",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 2,
            "smpName": "8033 Treatment 4",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 3,
            "smpName": "8034 Treatment 3",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 4,
            "smpName": "8034 Treatment 4",
            "smpType": "Sample",
            "smpData": []
          }
        ],
        "questions": [
          {
            "qNum": 1,
            "aNum": 1,
            "qName": "Rank the tomato samples based on overall liking of flavor",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "ranksamples",
            "descriptors": []
          },
          {
            "qNum": 2,
            "aNum": 1,
            "qName": "Group samples based on texture similarities - i.e. thickness of skin, bursting, chewy, etc",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "freesort",
            "descriptors": []
          },
          {
            "qNum": 3,
            "aNum": 1,
            "qName": "Which survey platform do you prefer for sensory evaluations",
            "qDisplay": "Once (not sample related)",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "choice",
            "descriptors": [
              { "value": 1.0, "text": "RStudio Survey" },
              { "value": 2.0, "text": "CompuSense" }
            ]
          },
          {
            "qNum": 4,
            "aNum": 1,
            "qName": "Any additional comments/questions/suggestions",
            "qDisplay": "Once (not sample related)",
            "required": false,
            "branch": "",
            "eCriteria": "",
            "qType": "comment",
            "descriptors": []
          }
        ]
      }
    ]
  },
  {
    "testID": 44,
    "testName": "Laramie Raspberry Standard test 2/22",
    "testType": "Standard",
    "day": "31",
    "month": "5",
    "year": "2022",
    "location": "Evaluation Tests",
    "folderPath": "Plenty\\All tests\\Evaluation Tests",
    "customTestProperties": [],
    "tags": [],
    "sections": [
      {
        "sectionNum": 1,
        "sectionName": "First Section",
        "testType": "Standard",
        "design": "D-44",
        "designName": "Williams Design (1 Latin Square)",
        "smps": [
          {
            "smpNum": 1,
            "smpName": "1109 Row 1",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 2,
            "smpName": "1109 Row 2",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 3,
            "smpName": "Let your soul shine Raspberries",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 4,
            "smpName": "Peak Quality Raspberries",
            "smpType": "Sample",
            "smpData": []
          }
        ],
        "questions": [
          {
            "qNum": 1,
            "aNum": 1,
            "qName": "Rank based on overall liking",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "ranksamples",
            "descriptors": []
          },
          {
            "qNum": 2,
            "aNum": 1,
            "qName": "Intensity of Raspberry flavor - Raspberry intensity",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
            "eCriteria": "",
            "qType": "category",
            "descriptors": [
              { "value": 1.0, "text": "Low" },
              { "value": 2.0, "text": "" },
              { "value": 3.0, "text": "" },
              { "value": 4.0, "text": "" },
              { "value": 5.0, "text": "" },
              { "value": 6.0, "text": "" },
              { "value": 7.0, "text": "" },
              { "value": 8.0, "text": "" },
              { "value": 9.0, "text": "High" }
            ]
          }
        ]
      }
    ]
  },
  {
    "testID": 45,
    "testName": "Laramie Tomato standard test 2/23",
    "testType": "Standard",
    "day": "31",
    "month": "5",
    "year": "2022",
    "location": "Evaluation Tests",
    "folderPath": "Plenty\\All tests\\Evaluation Tests",
    "customTestProperties": [],
    "tags": [],
    "sections": [
      {
        "sectionNum": 1,
        "sectionName": "First Section",
        "testType": "Standard",
        "design": "D-45",
        "designName": "Williams Design (1 Latin Square)",
        "smps": [
          {
            "smpNum": 1,
            "smpName": "8033 Treatment 1",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 2,
            "smpName": "8033 Treatment 2",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 3,
            "smpName": "8034 Treatment 1",
            "smpType": "Sample",
            "smpData": []
          },
          {
            "smpNum": 4,
            "smpName": "8034 Treatment 2",
            "smpType": "Sample",
            "smpData": []
          }
        ],
        "questions": [
          {
            "qNum": 1,
            "aNum": 1,
            "qName": "Overall liking",
            "qDisplay": "For all samples",
            "required": true,
            "branch": "",
